/* ─── Données fictives pour Alertes Foncier Pro ─── */

import type {
  AlertUserProfile,
  AlertZone,
  AlertEvent,
  AlertActivityStats,
  NotificationPreferences,
  AdvancedFilters,
  AlertTypeKey,
  OnboardingStep,
} from '@/types/alerts';

// ── Profil utilisateur fictif ──
export const MOCK_USER_PROFILE: AlertUserProfile = {
  id: 'usr_001',
  email: 'jean.dupont@agence-caraibes.com',
  emailVerified: true,
  phone: '+596 690 12 34 56',
  phoneVerified: true,
  fullName: 'Jean Dupont',
  agencyName: 'Agence Caraïbes Immobilier',
  territory: 'guadeloupe',
  timezone: 'America/Guadeloupe',
};

// ── Zones d'alerte fictives ──
export const MOCK_ALERT_ZONES: AlertZone[] = [
  {
    id: 'zone_001',
    userId: 'usr_001',
    name: 'Baie-Mahault Centre',
    zoneType: 'commune',
    communes: ['Baie-Mahault'],
    isActive: true,
    createdAt: '2025-11-15T10:30:00Z',
  },
  {
    id: 'zone_002',
    userId: 'usr_001',
    name: 'Zone Projet Route du Rhum',
    zoneType: 'polygon',
    geometry: {
      type: 'Polygon',
      coordinates: [
        [
          [-61.58, 16.28],
          [-61.55, 16.28],
          [-61.55, 16.25],
          [-61.58, 16.25],
          [-61.58, 16.28],
        ],
      ],
    },
    isActive: true,
    createdAt: '2025-12-01T14:00:00Z',
  },
  {
    id: 'zone_003',
    userId: 'usr_001',
    name: 'Pointe-à-Pitre Port',
    zoneType: 'radius',
    center: { lat: 16.2411, lng: -61.5331 },
    radiusKm: 3,
    isActive: false,
    createdAt: '2026-01-10T08:00:00Z',
  },
];

// ── Types d'alertes activés fictifs ──
export const MOCK_ENABLED_ALERT_TYPES: AlertTypeKey[] = [
  'NEW_LISTING',
  'PRICE_DROP',
  'PLU_CHANGE',
  'NEW_ARRETE',
  'INFRASTRUCTURE',
  'RISK_PPRI',
];

// ── Préférences de notification fictives ──
export const MOCK_NOTIFICATION_PREFS: NotificationPreferences = {
  smsAlerts: 'urgent_only',
  emailAlerts: 'immediate',
  digestFrequency: 'daily',
  digestTime: '08:00',
  websocketToasts: true,
  soundNotifications: true,
  quietHoursStart: '22:00',
  quietHoursEnd: '07:00',
};

// ── Filtres avancés fictifs ──
export const MOCK_ADVANCED_FILTERS: AdvancedFilters = {
  minSurface: 500,
  maxSurface: 10000,
  priceMin: 50000,
  priceMax: 500000,
  parcelTypes: ['constructible'],
  zonagePLU: ['U', 'AU'],
  buildableOnly: true,
};

// ── Événements d'alerte fictifs ──
export const MOCK_ALERT_EVENTS: AlertEvent[] = [
  {
    id: 'evt_001',
    alertConfigId: 'cfg_001',
    type: 'NEW_LISTING',
    priority: 'standard',
    title: 'Nouveau terrain à Baie-Mahault',
    summary: 'Parcelle constructible de 850 m² mise en vente à 185 000 €',
    details:
      'Une nouvelle parcelle constructible (zone U) de 850 m² a été mise en vente dans le secteur de Baie-Mahault Centre. Prix demandé : 185 000 €. Ref. parcelle : AB-0234. Viabilisée, accès route départementale.',
    zoneName: 'Baie-Mahault Centre',
    commune: 'Baie-Mahault',
    parcelRef: 'AB-0234',
    channels: ['email', 'websocket'],
    read: false,
    createdAt: '2026-03-03T09:42:00Z',
    emailSentAt: '2026-03-03T09:42:15Z',
  },
  {
    id: 'evt_002',
    alertConfigId: 'cfg_001',
    type: 'PLU_CHANGE',
    priority: 'urgent',
    title: 'Modification PLU – Baie-Mahault',
    summary: 'Zone NC reclassée en AU : 12 hectares deviennent constructibles',
    details:
      "Le conseil municipal de Baie-Mahault a approuvé la modification n°3 du PLU. La zone NC (naturelle) du secteur Destrellan est reclassée en AU (à urbaniser). 12 hectares de terrains agricoles deviennent potentiellement constructibles. Enquête publique terminée le 15/02/2026.",
    zoneName: 'Baie-Mahault Centre',
    commune: 'Baie-Mahault',
    channels: ['sms', 'email', 'websocket'],
    read: false,
    createdAt: '2026-03-02T14:30:00Z',
    emailSentAt: '2026-03-02T14:30:10Z',
    smsSentAt: '2026-03-02T14:30:05Z',
  },
  {
    id: 'evt_003',
    alertConfigId: 'cfg_001',
    type: 'PRICE_DROP',
    priority: 'standard',
    title: 'Baisse de prix – Terrain Route du Rhum',
    summary: 'Terrain de 1 200 m² passe de 220 000 € à 189 000 € (-14%)',
    details:
      "Le terrain situé au lieu-dit \"Les Hauts du Gosier\" (parcelle CD-0567) a vu son prix baisser de 14%. Ancien prix : 220 000 €. Nouveau prix : 189 000 €. Constructible (zone U), 1 200 m². En vente depuis 6 mois.",
    zoneName: 'Zone Projet Route du Rhum',
    commune: 'Le Gosier',
    parcelRef: 'CD-0567',
    channels: ['email', 'websocket'],
    read: true,
    createdAt: '2026-03-01T11:15:00Z',
    emailSentAt: '2026-03-01T11:15:20Z',
  },
  {
    id: 'evt_004',
    alertConfigId: 'cfg_001',
    type: 'INFRASTRUCTURE',
    priority: 'standard',
    title: 'Nouveau projet routier – Baie-Mahault',
    summary: 'Extension de la voie de liaison Jarry-Destrellan annoncée',
    details:
      "La communauté d'agglomération Cap Excellence a voté le financement de l'extension de la voie de liaison Jarry-Destrellan. Coût estimé : 28 M€. Début des travaux prévu T3 2026. Impact positif sur la desserte des parcelles situées dans le secteur.",
    zoneName: 'Baie-Mahault Centre',
    commune: 'Baie-Mahault',
    channels: ['email'],
    read: true,
    createdAt: '2026-02-28T16:00:00Z',
    emailSentAt: '2026-02-28T16:00:30Z',
  },
  {
    id: 'evt_005',
    alertConfigId: 'cfg_001',
    type: 'RISK_PPRI',
    priority: 'urgent',
    title: 'Mise à jour PPRI – Pointe-à-Pitre',
    summary: "Nouvelle cartographie des zones inondables publiée par la préfecture",
    details:
      "La préfecture de Guadeloupe a mis à jour le Plan de Prévention du Risque Inondation (PPRI) pour le secteur de Pointe-à-Pitre et communes limitrophes. Certaines parcelles précédemment en zone bleue passent en zone rouge. Consultez la nouvelle carte sur le site de la préfecture.",
    zoneName: 'Pointe-à-Pitre Port',
    commune: 'Pointe-à-Pitre',
    channels: ['sms', 'email', 'websocket'],
    read: true,
    createdAt: '2026-02-25T08:30:00Z',
    emailSentAt: '2026-02-25T08:30:15Z',
    smsSentAt: '2026-02-25T08:30:10Z',
  },
  {
    id: 'evt_006',
    alertConfigId: 'cfg_001',
    type: 'NEW_ARRETE',
    priority: 'urgent',
    title: 'Arrêté municipal – Permis de lotir',
    summary: 'Nouveau lotissement autorisé à Baie-Mahault (24 lots)',
    details:
      "L'arrêté n°2026-045 du 20/02/2026 autorise la création d'un lotissement de 24 lots constructibles au lieu-dit \"Morne Bernard\" à Baie-Mahault. Surface totale : 2.8 hectares. Lots de 400 à 800 m². Aménageur : SCI Les Balisiers.",
    zoneName: 'Baie-Mahault Centre',
    commune: 'Baie-Mahault',
    channels: ['email', 'websocket'],
    read: false,
    createdAt: '2026-02-20T10:00:00Z',
    emailSentAt: '2026-02-20T10:00:25Z',
  },
  {
    id: 'evt_007',
    alertConfigId: 'cfg_001',
    type: 'NEW_LISTING',
    priority: 'standard',
    title: 'Terrain agricole à Le Gosier',
    summary: 'Parcelle agricole de 3 500 m² mise en vente à 95 000 €',
    details:
      'Une parcelle agricole (zone A) de 3 500 m² a été mise en vente dans le secteur du Gosier. Prix demandé : 95 000 €. Ref. parcelle : EF-0891. Accès par chemin communal. Non viabilisée.',
    zoneName: 'Zone Projet Route du Rhum',
    commune: 'Le Gosier',
    parcelRef: 'EF-0891',
    channels: ['email'],
    read: true,
    createdAt: '2026-02-18T15:20:00Z',
    emailSentAt: '2026-02-18T15:20:30Z',
  },
];

// ── Statistiques d'activité fictives ──
export const MOCK_ACTIVITY_STATS: AlertActivityStats = {
  alertsThisMonth: 23,
  smsSent: 8,
  emailsSent: 23,
  lastAlertAt: '2026-03-03T09:42:00Z',
};

// ── Étapes d'intégration fictives ──
export const MOCK_ONBOARDING_STEPS: OnboardingStep[] = [
  { id: 1, label: 'Créer un compte', required: true, completed: true },
  { id: 2, label: "Vérifier l'email", required: true, completed: true },
  { id: 3, label: 'Ajouter un numéro de téléphone', required: true, completed: true },
  { id: 4, label: 'Vérifier le téléphone (OTP)', required: true, completed: true },
  { id: 5, label: 'Sélectionner un territoire', required: true, completed: true },
  { id: 6, label: "Créer une première zone d'alerte", required: true, completed: true },
  { id: 7, label: "Choisir les types d'alertes", required: true, completed: true },
  { id: 8, label: 'Configurer les notifications', required: true, completed: true },
  { id: 9, label: 'Tester une alerte (SMS/Email)', required: false, completed: false },
];

// ── Communes par territoire (pour création de zone) ──
export const COMMUNES_BY_TERRITORY: Record<string, string[]> = {
  guadeloupe: [
    'Anse-Bertrand',
    'Baie-Mahault',
    'Baillif',
    'Basse-Terre',
    'Bouillante',
    'Capesterre-Belle-Eau',
    'Capesterre-de-Marie-Galante',
    'Deshaies',
    'Gourbeyre',
    'Goyave',
    'Grand-Bourg',
    'La Désirade',
    'Lamentin',
    'Le Gosier',
    'Le Moule',
    'Les Abymes',
    'Morne-à-l\'Eau',
    'Petit-Bourg',
    'Petit-Canal',
    'Pointe-Noire',
    'Pointe-à-Pitre',
    'Port-Louis',
    'Saint-Claude',
    'Saint-François',
    'Saint-Louis',
    'Sainte-Anne',
    'Sainte-Rose',
    'Terre-de-Bas',
    'Terre-de-Haut',
    'Trois-Rivières',
    'Vieux-Fort',
    'Vieux-Habitants',
  ],
  martinique: [
    'Basse-Pointe',
    'Bellefontaine',
    'Case-Pilote',
    'Ducos',
    'Fonds-Saint-Denis',
    'Fort-de-France',
    'Grand-Rivière',
    'Gros-Morne',
    'L\'Ajoupa-Bouillon',
    'La Trinité',
    'Le Carbet',
    'Le Diamant',
    'Le François',
    'Le Lamentin',
    'Le Lorrain',
    'Le Marigot',
    'Le Marin',
    'Le Morne-Rouge',
    'Le Morne-Vert',
    'Le Prêcheur',
    'Le Robert',
    'Le Vauclin',
    'Les Anses-d\'Arlet',
    'Les Trois-Îlets',
    'Macouba',
    'Rivière-Pilote',
    'Rivière-Salée',
    'Saint-Esprit',
    'Saint-Joseph',
    'Saint-Pierre',
    'Sainte-Anne',
    'Sainte-Luce',
    'Sainte-Marie',
    'Schœlcher',
  ],
  guyane: [
    'Awala-Yalimapo',
    'Camopi',
    'Cayenne',
    'Grand-Santi',
    'Kourou',
    'Macouria',
    'Mana',
    'Maripasoula',
    'Matoury',
    'Montsinéry-Tonnegrande',
    'Ouanary',
    'Papaïchton',
    'Régina',
    'Remire-Montjoly',
    'Roura',
    'Saint-Élie',
    'Saint-Georges',
    'Saint-Laurent-du-Maroni',
    'Saül',
    'Sinnamary',
    'Iracoubo',
  ],
  reunion: [
    'Bras-Panon',
    'Cilaos',
    'Entre-Deux',
    'L\'Étang-Salé',
    'La Plaine-des-Palmistes',
    'La Possession',
    'Le Port',
    'Le Tampon',
    'Les Avirons',
    'Les Trois-Bassins',
    'Petite-Île',
    'Saint-André',
    'Saint-Benoît',
    'Saint-Denis',
    'Saint-Joseph',
    'Saint-Leu',
    'Saint-Louis',
    'Saint-Paul',
    'Saint-Philippe',
    'Saint-Pierre',
    'Sainte-Marie',
    'Sainte-Rose',
    'Sainte-Suzanne',
    'Salazie',
  ],
};
